# Generated by Django 4.1.7 on 2023-03-03 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raterprojectapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.CharField(default='This Game Sucks!', max_length=500),
            preserve_default=False,
        ),
    ]
